### ISSUE TITLE
Can you please mention clear instructions to run this, I needed to figure out the DB details and all, still not able to login to leave mgmt web pages

### ISSUE THREAD

**Issue by Arnab1996** [NaveenKumarK219/leave-management-system#2]
Can you please mention clear instructions to run this, I needed to figure out the DB details and all, still not able to login to leave mgmt web pages

**Comment by NaveenKumarK219** [comment]
Hi @Arnab1996 Thanks for checking out this repository, and As you requested i've added the details for running the application.
