### ISSUE TITLE
confusion about postgresql

### ISSUE THREAD

**Issue by SaiAvinashP** [NaveenKumarK219/leave-management-system#4]
hi bro.. Such a nice project .. i'm new to spring boot & PostgreSQL ... actually i'm using MySQL .. if you don't mind.. can you please make a queries on MySQL instead of PostgreSQL ...

**Comment by NaveenKumarK219** [comment]
Hey @SaiAvinashP , Thanks for going around the repositories and glad that you liked it. And coming to your question, i don't think there will be much difference in the queries for MYSql, you can run them as it is.
