### ISSUE TITLE
Calendar dates dont have colors

### ISSUE THREAD

**Issue by syed0901** [NaveenKumarK219/leave-management-system#5]
First of all. Great project!
I have 2 issues:

1. When I click on Submit on Apply Leave, it doesn't go to landing page. It shows Whitelabel error page. I click back. I see results properly done in the database though.

2. The Calendar on home screen does not show blue, green and red colors in dates which are put on leave. Even when i click Pending, Accepted and Rejected checkboxes.

**Comment by syed0901** [comment]
First issue is resolved. There was some wrong landing views with "leave-management-system" is URL

**Comment by syed0901** [comment]
Second issue is resolved. date format in SimpleDateFormat should YYYY-MM-dd, instead of YYYY-MM-DD.
Thank you.

**Comment by SaiAvinashP** [comment]
Hello bro.. i'm also getting an error in date format .. actually i'm using mysql instead of postgresql ... 
"from_date timestamp without time zone NOT NULL," .. can you tell me how to write this line in mysql ...

**Comment by NaveenKumarK219** [comment]
Hey @SaiAvinashP I'm not sure on MySql. And @syed0901 Glad that you liked my project.
